name: CD - Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: âœ¨ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ§ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: âš’ï¸ Build and push ml-api image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile_api_full
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ml-api:latest

      - name: âš’ï¸ Build and push ml-frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile_frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ml-frontend:latest
