name: CI - Build, Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: âœ¨ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ§ Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: ğŸ“ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: âš’ï¸ Build API Docker image
        run: docker build -f Dockerfile_api_full -t ml-api-test .

      - name: âš’ï¸ Build Frontend Docker image
        run: docker build -f Dockerfile_frontend -t ml-frontend-test .

      - name: âœï¸ Lint code with flake8
        run: |
          echo "Linting with flake8..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: ğŸ”® Format check with black
        run: black --check .

      - name: ğŸ¤” Run unit tests with pytest
        run: pytest tests/

      - name: âœ… CI terminÃ© avec succÃ¨s
        run: echo "ğŸš€ Tout est OK !"
